document.writeln("<!-- 公用底部 -->");
document.writeln("<div class=\'isbottom\'>");
document.writeln("    <div class=\'isbottom_all\'>");
document.writeln("        <div class=\'isbottom_l\'>");
document.writeln("            <div class=\'isbottom_l_top\'>");
document.writeln("                <ul>");
document.writeln("                    <li class=\'car\'>所有车型</li>");
document.writeln("                    <li class=\'car\'>所有车型</li>");
document.writeln("                    <li class=\'car\'>所有车型</li>");
document.writeln("                </ul>");
document.writeln("                ");
document.writeln("            </div>");
document.writeln("            <div class=\'isbottom_l_bottom\'>");
document.writeln("                <ul>");
document.writeln("             ");
document.writeln("                <li>祺智PHEV</li>");
document.writeln("                <li>2019款柏罗杰</li>");
document.writeln("                <li>2018款欧蓝德</li>");
document.writeln("                <li>2018款欧蓝德</li>");
document.writeln("            </ul>");
document.writeln("            <ul>");
document.writeln("              ");
document.writeln("                <li>祺智PHEV</li>");
document.writeln("                <li>2019款柏罗杰</li>");
document.writeln("                <li>2018款欧蓝德</li>");
document.writeln("                <li>2018款欧蓝德</li>");
document.writeln("            </ul>");
document.writeln("            <ul>");
document.writeln("              ");
document.writeln("                <li>祺智PHEV</li>");
document.writeln("                <li>2019款柏罗杰</li>");
document.writeln("                <li>2018款欧蓝德</li>");
document.writeln("                <li>2018款欧蓝德</li>");
document.writeln("            </ul>");
document.writeln("            </div>");
document.writeln("            ");
document.writeln("        </div>");
document.writeln("        <div class=\'isbottom_r\'>");
document.writeln("            <div class=\'isbottom_r_l\'>");
document.writeln("                <div class=\'isbottom_r_l_l\'>");
document.writeln("                    <img src=\'./imgs/erweima1.png\' width=\'80px\' height=\'80px\' alt=\'\'><br>");
document.writeln("                    关注新浪微博");
document.writeln("                </div>");
document.writeln("                <div class=\'isbottom_r_l_r\'>");
document.writeln("                    <img src=\'./imgs/erweima1.png\' width=\'80px\' height=\'80px\' alt=\'\'><br>");
document.writeln("                    关注微信公众号");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("            <div class=\'isbottom_r_r\'>");
document.writeln("                <h1>400-4423131</h1>");
document.writeln("                <span>24小时服务热线</span><br>");
document.writeln("                <button><span></span>联系客服</button>");
document.writeln("");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'isbottom_b\'>");
document.writeln("            <div class=\'isbottom_b_l\'>");
document.writeln("                关注我们");
document.writeln("                <span></span>");
document.writeln("                <span></span>");
document.writeln("            </div>");
document.writeln("            <div class=\'isbottom_b_r\'>");
document.writeln("                服务热线: 131223-12121-1212121");
document.writeln("            </div>");
document.writeln("    </div>");
document.writeln("</div>");