document.writeln("<!-- 公用头部 -->");
document.writeln("<div class=\'top\'>");
document.writeln("    <div class=\'left\'>");
document.writeln("    <span></span>");
document.writeln("        上海");
document.writeln("    </div>");
document.writeln("    <div class=\'right\'>");
document.writeln("        <ul>");
document.writeln("            <li><a href=\'\'>登录</a></li>");
document.writeln("            <li><a href=\'\'>注册</a></li>");
document.writeln("            <li><a href=\'\'>我的订单");
document.writeln("            <span></span>");
document.writeln("            </a></li>");
document.writeln("            <li><a href=\'\'>在线咨询</a></li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<div class=\'header\'>");
document.writeln("            <div class=\'nav\'>");
document.writeln("                <a class=\'logo\'>");
document.writeln("                    <img src=\'http://119.254.195.229/imgIndex/logo1.png\'>");
document.writeln("                </a>");
document.writeln("                <ul class=\'nav_list\'>");
document.writeln("                    <li><a href=\'\'>首页</a></li>");
document.writeln("                    <li><a href=\'\'>所有车型</a></li>");
document.writeln("                    <li><a href=\'\'>新车上市</a></li>");
document.writeln("                    <li><a href=\'\'>预约试驾</a></li>");
document.writeln("                    <li><a href=\'\'>在线订车</a></li>");
document.writeln("                    <li><a href=\'\'>经销商查询</a></li>");
document.writeln("                </ul>");
document.writeln("                <div class=\'nav_right\'>");
document.writeln("                     <input type=\'text\' placeholder=\'输入关键字\'>");
document.writeln("                     <span></span>");
document.writeln("                </div>");
document.writeln("               ");
document.writeln("            </div>");
document.writeln("</div>");